FROM ubuntu:14.04

MAINTAINER  Gerald Leenerts <gleenerts@lifetimefitness.com>

ENV SCALA_VERSION 2.11.4
ENV SBT_VERSION 0.13.8

# INSTALL OS DEPENDENCIES
RUN apt-get update && apt-get install -y \
    git \
    software-properties-common \
    unzip \
    curl \
    openssl \
    wget

# INSTALL JAVA 8
RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    apt-get install -y oracle-java8-installer

# Install Scala
RUN apt-get remove scala-library scala
RUN wget www.scala-lang.org/files/archive/scala-$SCALA_VERSION.deb
RUN dpkg -i scala-$SCALA_VERSION.deb
RUN apt-get install scala
RUN rm scala-$SCALA_VERSION.deb

# Install SBT
RUN wget http://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
RUN dpkg -i sbt-$SBT_VERSION.deb
RUN apt-get install sbt
RUN rm sbt-$SBT_VERSION.deb

# - - -
# Everything above this,
# should probably be on a root development image once more people finalize it.
# - - -

# Install wkhtmltopdf
RUN apt-get install -y wkhtmltopdf

WORKDIR /root/
